FROM python:3.8-slim-buster


COPY ["requirements.txt","learner/src","params/params_py.config","/app/src/"]
COPY logger/logger.py /logger/logger.py
RUN python -m pip install --upgrade setuptools pip wheel
WORKDIR /app/src
RUN yes | pip install -r requirements.txt
CMD python ./tweet-learner.py params_py.config
